EUDAT-GEF/GEF

- backend-docker/dckr/dckr.go
- backend-docker/server/apiserver.go
- services/volume-filelist/Dockerfile
- services/volume-filelist/Makefile.txt
- services/volume-filelist/main.go
- services/volume-inspector/Dockerfile
- services/volume-inspector/api/api.go
Uses Docker remote API directly
> API call to get files from a container/volume

- services/stanford-parser/Dockerfile
- services/wfcatalog-collector-demo/Dockerfile
Two new services have been added for the demo: WFCatalog Collector and Stanford Parser for English. They do not write anything into output volumes, the results are displayed in a console.
> Added two services for the demo

- frontend/src/main/resources/assets/css/base.css
- frontend/src/main/webui/src/components/Job.jsx
- frontend/src/main/webui/src/components/Jobs.jsx
- frontend/src/main/webui/src/components/Service.jsx
- frontend/src/main/webui/src/components/Services.jsx
I also added a very simple animation to indicate that something is being done.
> Job status message styling has been changed, service and job list layouts as well

- services/ENES-demo/Dockerfile
This service allow to download a netcdf file and average it using ncwa command from the nco library set up in the container. This kind of calculation is typically used to compare climate trend across the time. Other calculations, such as root mean square, could be performed by changing the CMD command in the Dockerfile.
Any users interested to test this GEF service might submit the following PID:
11304/30c015aa-b988-11e3-8cd7-14feb57d12b9
It will download a 10 years time series of the pressure sea level and return the time series average as output.
> Added ENES demo

- frontend/webui/src/actions/actions.jsx
- frontend/webui/src/components/Service.jsx
- frontend/webui/src/components/Services.jsx
When service metadata is updated, the list of services is also updated on the client side
> Service metadata update

- README.md
- gefserver/db/db.go
- gefserver/db/service.go
- gefserver/pier/internal/dckr/dckr.go
- gefserver/pier/pier.go
- gefserver/pier/staging.go
The GEF can work with the Docker swarm mode now. Change config.json according to the instructions from the ReadMe to activate swarm mode
> Swarm service execution

- gefserver/db/db.go
- gefserver/pier/internal/dckr/dckr.go
- gefserver/pier/pier.go
Solves the issue https://github.com/EUDAT-GEF/GEF/issues/109
> Solved the cmd issue

- gefserver/pier/internal/dckr/dckr.go
It seems to solve the issue https://github.com/EUDAT-GEF/GEF/issues/108
> Added restart policy for swarm services

- services/_internal/volume-stage-in/main.py
Case insensitive check of the "content-disposition" header. Now it does not fail, if the header is not there
> Checking headers while running the data staging contianer

- gefserver/pier/internal/dckr/dckr.go
Fixes the problem caused by the docker API update
> Changed type for swarm.ContainerSpec

- .gitignore
- Dockerfile
- Makefile
After having problems with building binaries under Ubuntu, we decided to create a dedicated Ubuntu docker image
> Build a linux binary in an Ubuntu 16.04 container

- gefserver/config.json
- gefserver/def/config.go
- gefserver/server/api.go
- webui/src/components/Footer.jsx
- webui/src/containers/FooterContainer.jsx
closes https://github.com/EUDAT-GEF/GEF/issues/123
> Fix contact link

- .gitignore
- .travis.yml
- Makefile
- README.md
- gefserver/glide.lock
- gefserver/glide.yaml
- gefserver/pier/internal/dckr/dckr.go
fixes https://github.com/EUDAT-GEF/GEF/issues/68
> Add vendoring solution: glide

- gefserver/pier/internal/dckr/dckr.go
- gefserver/pier/pier.go
- gefserver/pier/staging.go
Looks like it solves the issue https://github.com/EUDAT-GEF/GEF/issues/133
> Removing containers used to download files from volumes

- gefserver/config.json
- gefserver/def/config.go
- gefserver/main.go
- gefserver/pier/internal/dckr/dckr.go
- gefserver/pier/pier.go
- gefserver/tests/pier_test.go
- gefserver/tests/server_test.go
- gefserver/tests/swarm_test.go
- gefserver/tests/timeout_test/Dockerfile
It is supposed to close the issue https://github.com/EUDAT-GEF/GEF/issues/92
> Proper timeouts for jobs

- gefserver/pier/pier.go
- gefserver/server/access.go
- gefserver/tests/server_test.go
- webui/src/actions/actions.jsx
- webui/src/components/User.jsx
fixes https://github.com/EUDAT-GEF/GEF/issues/144
> More tests, code cleanup, roles in user profile

- .gitignore
- Dockerfile
- Makefile
- gefserver/pier/pier.go
- webui/copy_files.sh
- webui/src/components/Jobs.jsx
Packaging now works with Glide. Job finish time bug was detected and fixed: finish time is set when a job fails or finishes successfully
> Packaging supports the official vendoring solution

- gefserver/config.json
- gefserver/server/api.go
- gefserver/server/events.go
The GEF sends information about an active current user to the Drools rule engine system, if it was specified in the config
> Initial Drools support

- gefserver/config.json
- gefserver/db/accounts.go
- gefserver/db/db.go
- gefserver/def/config.go
- gefserver/main.go
- gefserver/pier/pier.go
- gefserver/pier/staging.go
- gefserver/server/api.go
- gefserver/server/events.go
- gefserver/tests/pier_test.go
- gefserver/tests/server_test.go
- gefserver/tests/swarm_test.go
We started integrating a rule engine system with the GEF. It requires some changes in the GEF: it has to send information about its configuration to Drools, Drools checks the rules, modifies this configuration (if necessary), and sends it back to the GEF
> Rule engine partial integration

- README.md
- examples/jobStart.py
An small example that helps to get started with the GEF API (supports multiple job inputs)
> Python script to illustrate an interaction with the GEF API

- webui/package-lock.json
- webui/package.json
- webui/src/components/Jobs.jsx
Sorting by date was not working correctly (columns were sorted as if they were strings), there used to be warnings while rendering the jobs table (keys were not unique). These problems are not fixed.
> Fixes jobs table sorting bug and warnings

- gefserver/db/build.go
- gefserver/server/api.go
- webui/src/components/Files.jsx
Error messages are displayed correctly and the building process is terminated if there is no Dockerfile or tar archive
> Fixing the issues while building an image
